### PR TITLE
XTCE alignment

### PR DESCRIPTION
**Pull request by wkbrd**
Recommend adding this section that covers XTCE Alarm color alignment to C2MS and AstroUX.  Please contact me if you have questions.

### CODE REVIEW

**Comment by amalyah** [comment]
@wkbrd Thank you so much for submitting an update! 

We would love to talk to you to get a clearer understanding of which document this information is coming from so we can confirm the recommendations and the best place to put this guidance on our page. If you would be comfortable with having a meeting with us, please email support@astrouxds.com so we can schedule a conversation.

CC: @dmcalester

**Comment by wkbrd** [comment]
Hi @dmcalester , @amalyah ,

I appreciated the chat that we had a couple weeks ago.  Is there a status update on this pull request (change request)?  Is a draft of the website available to see at this point?

Thanks and have a nice day!

**Comment by amalyah** [comment]
> 

@wkbrd The content is ready for posting online. Next step is to get one of our devs to update the content online. In the meantime, we've already got a text revision ticket in the works which is in final content reviews, so the online posting may wait until that effort is completed. (Shouldn't take too long.) Thanks for checking in!

**Comment by wkbrd** [comment]
Hi all, the changes that were just merged do not reflect our meeting together.  Is that planned via a follow-up PR?

**Comment by amalyah** [comment]
> 
That was a mistake from a dev who saw my comment and jumped on it. Sorry about that! Currently unmerging that work and will be replacing it with what we have discussed previously.

**Comment by amalyah** [comment]
@wkbrd Thank you for your patience. The updated content is up on the website now!
https://www.astrouxds.com/platforms/astro-for-r2c2/#xtce-alarm-levels

**Comment by wkbrd** [comment]
Since the WATCH level is now assigned to caution/YELLOW, it the text above is incorrect.  This text should be changed:

_Since AstroUX does not define Watch or Severe levels, the next less critical level is recommended._

A suggestion for the update would be:

_Since AstroUX does not define Watch or Severe levels, Watch is mapped to the same coloring as Warning and Several is mapped to the same coloring as Critical._

**Comment by amalyah** [comment]
> Since the WATCH level is now assigned to caution/YELLOW, it the text above is incorrect. This text should be changed:
> 
> _Since AstroUX does not define Watch or Severe levels, the next less critical level is recommended._
> 
> A suggestion for the update would be:
> 
> _Since AstroUX does not define Watch or Severe levels, Watch is mapped to the same coloring as Warning and Severe is mapped to the same coloring as Critical._

We've made the change in the linked PR: https://github.com/RocketCommunicationsInc/astro-www/pull/335.
Thanks for the comment!

**Pull request merged**
