### PR TITLE
(redesign): got rid of unnecessary links, put correct paths on links …

### PR DESCRIPTION
**Pull request by Paterma**
…in footer, updated css for links

### CODE REVIEW

**Review by jonathantneal — APPROVED** [review]
Thank you. This will really polish the footer.

**Review by Paterma — COMMENTED** [review]
Double checked, good to go!

**Comment by jonathantneal** [comment]
Yes! Thank you, @Paterma.

**Comment by Paterma** [comment]
Thank YOU! @jonathantneal

**Pull request merged**
